// Extended chapter content — loaded before script.js
// Adds: keyModels, colourAngle, leaderInAction, watchOut to each chapter.
window.CHAPTERS_EXTRA = {
  1:{
    keyModels:[
      {name:'The Leadership Pipeline (Charan, Drotter & Noel)',desc:'Six distinct passages from individual contributor to enterprise leader, each requiring new skills, time horizons, and work values. Most derailments happen at the very first passage — from managing self to managing others — because the competencies that earned the promotion actively work against the new role.'},
      {name:"Drucker's manager imperative",desc:"Peter Drucker argued that a manager is responsible for the application and performance of knowledge — not for the knowledge itself. The moment you begin to lead, your job is to make others effective, not to be the most effective person in the room yourself."},
    ],
    colourAngle:{
      red:'Reds adapt quickly to authority but may confuse control with leadership — they delegate tasks without delegating ownership, then reclaim work when it slips. The habit to break: solving problems personally to maintain the pace they could sustain alone.',
      yellow:'Yellows embrace the social dimension of leading naturally but may under-invest in follow-through systems, leaving their team energised and unclear on what is actually expected of them week to week.',
      green:'Greens are instinctively supportive but can struggle to hold people accountable — their discomfort with conflict means performance gaps are softened rather than named, and problems grow silently.',
      blue:'Blues often remain too deep in technical detail because the quality of the team\'s output feels uncertain. The work they can control directly feels safer than the ambiguity of coaching others to match their standard.',
    },
    leaderInAction:'A senior engineer is promoted to team lead. Their first instinct is to review every pull request personally — a habit that served them as a solo contributor. Within three weeks, reviews become a bottleneck, the team stops owning their own quality, and the engineer is working 70-hour weeks while their direct reports are underutilised. The shift required was simple but non-obvious: define the quality standard clearly, coach the team to meet it, and inspect the outcome rather than every step of the process.',
    watchOut:['Solving every problem personally — it feels like helping but signals distrust and blocks your team\'s growth.','Measuring your own success by how busy you are rather than how much your team delivers independently.','Holding onto technical tasks because they feel safer and more controllable than the messier work of developing people.'],
  },
  2:{
    keyModels:[
      {name:'DISC (Marston, 1928 — updated)',desc:'The earliest formulation of four behavioural axes: Dominance, Influence, Submission, Compliance — updated by later researchers into Dominance, Influence, Steadiness, Conscientiousness. The colour model is a plain-language rendering of DISC that makes it portable in real conversations.'},
      {name:'Surrounded by Idiots (Erikson, 2019)',desc:'The popular rendering of DISC that brought the four-colour framework to a mainstream audience. A useful entry point, though the original DISC research offers more nuance — particularly on blends and the context-dependence of behaviour.'},
      {name:'Social Styles (Wilson Learning)',desc:'A parallel four-quadrant model using Assertiveness and Responsiveness as axes — structurally identical to DISC. Its convergence with DISC and Myers-Briggs reinforces the underlying insight: two simple dimensions explain a large proportion of behavioural variation.'},
    ],
    colourAngle:{
      red:'Reds often see the colour model as useful for getting results from difficult people faster — but may resist being diagnosed themselves. Their risk: applying the model as a tool for control rather than genuine adaptation.',
      yellow:'Yellows immediately enjoy the colour language and use it in conversation — but may reduce it to social fuel rather than a precision instrument. They categorise quickly and move on rather than sitting with ambiguity.',
      green:'Greens find the model reassuring — it legitimises the relational instincts they already have. Their risk: using it to excuse avoiding a hard conversation ("they\'re just a Red — there\'s no point pushing back").',
      blue:'Blues want to understand the model\'s academic validity before applying it. Once satisfied, they apply it with precision — and may over-diagnose others or dismiss the model when a person\'s behaviour doesn\'t fit neatly.',
    },
    leaderInAction:'A manager uses the colour model before a difficult stakeholder meeting. She knows the CFO is strongly Blue — data-led, prone to withdrawing under pressure, sceptical of enthusiasm without evidence. Instead of her usual high-energy pitch, she prepares a structured brief: evidence first, conclusion second, three clear risks appended. She leaves silence after each key point rather than filling it. The meeting that previously stalled in scepticism ends with a funding decision inside 40 minutes.',
    watchOut:['Treating colour as a label rather than a lens — "she\'s just a Green" stops your curiosity at the moment it should start.','Believing you\'ve correctly diagnosed someone from a single interaction, especially under pressure — stress masks default style.','Ignoring the cultural baseline — an individual\'s colour sits on top of cultural norms, not independent of them.'],
  },
  3:{
    keyModels:[
      {name:'The Johari Window (Luft & Ingham, 1955)',desc:'A four-quadrant model of self-knowledge: Open (known to self and others), Hidden (known to self, not others), Blind Spot (known to others, not to self), Unknown. Feedback shrinks the Blind Spot; disclosure shrinks the Hidden area. For leaders, the Blind Spot quadrant is the highest-risk area.'},
      {name:'Internal vs. External Self-Awareness (Eurich, 2017)',desc:'Tasha Eurich\'s research found that while 95% of people believe they are self-aware, only 10–15% genuinely are. Critically, internal self-awareness (knowing your own emotions, values, patterns) and external self-awareness (knowing how others see you) are barely correlated — you need to build both independently.'},
    ],
    colourAngle:{
      red:'Reds often score high on internal self-awareness — they know what they want and why — but low on external. They underestimate the impact of their intensity and bluntness on others, especially those with less authority.',
      yellow:'Yellows have good external self-awareness (they read rooms quickly) but limited internal. They move so fast past discomfort that they may not know their own triggers — or how their optimism can be read as a lack of seriousness.',
      green:'Greens are externally aware but often suppress awareness of their own needs — prioritising others\' feelings to the point of not knowing what they themselves actually want from a situation.',
      blue:'Blues tend to over-analyse themselves internally but can be genuinely surprised by how others experience their emotional distance or critical tone — the gap between their intent and their impact is often wide.',
    },
    leaderInAction:'A VP discovers through a 360 that her team experiences her as intimidating — something that genuinely surprises her. She believed she was being clear and direct. After reviewing specific feedback, she notices a pattern: she asks questions in meetings that others experience as interrogations, not invitations. With this awareness in hand, she shifts her opening question from "Why wasn\'t this done?" to "Walk me through what happened." Team members begin speaking up in meetings within weeks. The same behaviour — asking questions — now lands as curiosity instead of criticism.',
    watchOut:['Assuming your self-assessment is accurate — the higher your position, the less corrective feedback arrives naturally.','Collecting insight without changing behaviour — awareness that produces no action is vanity, not leadership.','Seeking confirmation only from people who already like you, which reinforces your existing self-portrait rather than expanding it.'],
  },
  4:{
    keyModels:[
      {name:"Goleman's EI Framework (1995)",desc:'Five domains: Self-Awareness (knowing your emotions), Self-Regulation (managing them), Motivation (sustaining internal drive), Empathy (reading others), Social Skill (managing relationships effectively). EI, not IQ, is the stronger predictor of leadership effectiveness across most published research.'},
      {name:'The Amygdala Hijack (LeDoux / Goleman)',desc:'The amygdala processes emotional stimuli before the prefrontal cortex reaches them — emotion arrives before rational thought. The practical implication: under threat, leaders regress to instinctive emotional responses before they can choose a considered one. The gap between stimulus and response is where emotional skill lives.'},
    ],
    colourAngle:{
      red:'Reds often have high motivation and social assertiveness but lower empathy access and emotional regulation. Their fire drives performance but can intimidate and close down the honest conversation that high performance depends on.',
      yellow:'Yellows often have high empathy and social skill but lower self-regulation under stress — enthusiasm tips into scatter, and they may overpromise in emotionally charged moments without realising it.',
      green:'Greens have high empathy but may suppress their own emotional signals until they reach a breaking point. The emotional labour of carrying others\' feelings accumulates invisibly — until it becomes visible in ways that surprise everyone, including the Green.',
      blue:'Blues often have strong self-regulation (they control their emotional expression carefully) but lower empathy access and social expressiveness — they can read logic far more fluently than they can read feelings.',
    },
    leaderInAction:'A team lead receives a message at 10 pm from a key client threatening to escalate. His first reaction is fear and anger — fingers already hovering over the keyboard. He pauses, names what he is feeling ("this is anxiety and defensiveness"), and puts the phone face-down. In the morning, after sleep, he responds calmly and constructively to the substance of the complaint. The client later tells him that the measured reply was the reason they stayed rather than escalating. The message he wrote at 10 pm would have made things worse.',
    watchOut:['Confusing emotional suppression with emotional regulation — the first stores pressure, the second releases it. Both may look the same from outside but produce very different outcomes over time.','Underestimating how clearly your team reads your emotional state even when you believe you are hiding it.','Treating EI as a fixed trait — some people are naturally higher on specific dimensions, but every dimension is trainable with deliberate practice.'],
  },
  5:{
    keyModels:[
      {name:'Cognitive Reappraisal vs. Suppression (Gross, 1998)',desc:'Reappraising the meaning of a situation before emotion peaks — "this challenge is information I can use" rather than "this is a threat" — is more effective than suppressing the emotion after it has formed. Reappraisal costs less cognitive energy and produces better outcomes for both the person and those around them.'},
      {name:'The Window of Tolerance (Siegel)',desc:'The bandwidth within which effective functioning is possible — not too activated (fight/flight) and not too shut down (freeze). Practices that widen this window — regulated breathing, physical movement, named emotion — are the core composure tools. Narrow windows produce volatile leaders.'},
      {name:'The Pause Response',desc:'Between stimulus and response lies a gap. The work of self-regulation is to widen that gap deliberately — from milliseconds to seconds — so that a chosen response is possible. Physical anchors (a breath, a sip of water, standing up) work because they interrupt the automatic escalation pathway.'},
    ],
    colourAngle:{
      red:'Reds dysregulate most visibly — through impatience, sharpness, and verbal dominance. Recovery moves that work for Reds tend to be physical (a walk, a run) or task-based (completing one clear small thing to restore a sense of control and momentum).',
      yellow:'Yellows dysregulate into scattered energy and over-talking — filling silence with words as anxiety rises. Recovery requires grounding: a written list of the three things that matter today, or a short silence with a trusted colleague who can help them re-anchor.',
      green:'Greens dysregulate into withdrawal and passive avoidance — going quiet when they should speak and agreeing in the room when they disagree internally. Recovery often requires a direct, kind question from someone they trust: "What are you actually thinking right now?"',
      blue:'Blues dysregulate into hyper-analysis and paralysis — running more scenarios instead of fewer as the stakes rise. Recovery comes from narrowing scope deliberately: one decision, one question, one action. Reducing optionality breaks the loop.',
    },
    leaderInAction:'A director is challenged publicly in a board meeting on a project she owns. She feels heat in her face — the early signal of an amygdala hijack. Instead of defending immediately, she says: "That\'s a fair challenge. Let me make sure I answer it properly." The pause lasts 8 seconds — which feels much longer. Her prefrontal cortex engages. Her response is measured, acknowledges the legitimate concern, and offers a specific remedy. The questioner later praises her composure. The response she had on the tip of her tongue before the pause would have been accurate but defensive — and would have lost the room.',
    watchOut:['Treating composure as a performance you sustain until you break privately — the goal is regulation, not suppression.','Ignoring the physical early-warning signals (clenched jaw, shallow breathing, heat in the face) that arrive before full emotional escalation.','Using "staying calm" as a justification for avoiding difficult conversations entirely — composure enables hard conversations rather than replacing them.'],
  },
  6:{
    keyModels:[
      {name:'Three Types of Empathy (Goleman & Boyatzis)',desc:'Cognitive empathy (understanding how someone thinks and sees the world), emotional empathy (feeling what they feel), and empathic concern (sensing what they need and being moved to act on it). Leadership requires all three, in the right balance — emotional empathy alone can lead to over-identification; cognitive empathy alone can be cold and clinical.'},
      {name:'Active Listening (Rogers & Farson, 1957)',desc:'Listening not merely to understand content but to understand the person — their meaning, their emotion, and their perspective. Requires full attention, reflection back, and suspension of evaluation. The key test: can you articulate the other person\'s position as well as they can before you respond?'},
      {name:"Empathy vs. Sympathy (Brown)",desc:'Empathy fuels connection; sympathy drives disconnection. Empathy enters the other person\'s perspective; sympathy looks down on it from outside. Leaders default to sympathy without realising it — "at least you have..." is a sympathy move that often lands as diminishing.'},
    ],
    colourAngle:{
      red:'Reds\' empathy tends to be pragmatic — they want to understand someone\'s situation well enough to move past it to action. Deep emotional attunement feels inefficient. Their challenge: the person in front of them often cannot move to action until they first feel understood.',
      yellow:'Yellows feel empathy acutely and naturally — but can over-identify with others\' emotions, absorbing the team\'s anxiety and amplifying it rather than steadying it. The leader who weeps with the team provides comfort but not leadership.',
      green:'Greens are naturally empathic but their empathy can tip into over-accommodation — they remove the very discomfort that would help a person grow. Sometimes the most empathic move is to let someone sit with a hard truth long enough to respond to it.',
      blue:'Blues\' empathy is primarily cognitive — they understand a situation logically but may not acknowledge the emotional dimension. The person in front of them often experiences this as cold or uncaring, even when the Blue genuinely does care.',
    },
    leaderInAction:'A team member explains that she missed a key deadline because her mother had been hospitalised. The manager\'s first instinct is to problem-solve the recovery plan. Instead he pauses and says: "I\'m sorry. That must have been a really frightening week — how is she now?" The conversation shifts entirely. She feels seen rather than managed. Twenty minutes later she volunteers the recovery plan herself — more detailed and more committed than anything he would have proposed, because she owns it.',
    watchOut:['Jumping to problem-solving before the person feels heard — the solution will often be rejected because the person wasn\'t acknowledged first.','Over-empathising to the point of removing accountability — understanding someone\'s situation is not the same as excusing the impact of their behaviour on others.','Performing empathy (nodding, paraphrasing) without genuine curiosity about the other person\'s actual experience.'],
  },
  7:{
    keyModels:[
      {name:'Situational Leadership (Hersey & Blanchard, 1969)',desc:'Match leadership style (directing, coaching, supporting, delegating) to the individual\'s competence and commitment in the specific task. No single style works for everyone or in every situation — the diagnosis of what the person needs precedes the choice of how to lead them.'},
      {name:'The Platinum Rule',desc:'An upgrade on the Golden Rule: treat others as they want to be treated, not as you want to be treated. Applying the Platinum Rule requires genuine curiosity and observation rather than projection — the natural instinct is to treat others the way we would wish to be treated ourselves.'},
      {name:'Thomas–Kilmann Conflict Modes',desc:'Five responses to conflict — competing, collaborating, compromising, avoiding, accommodating — map closely onto colour defaults. Reds compete; Yellows avoid through charm; Greens accommodate; Blues analyse. Knowing your default mode is the first step to choosing the mode that the situation actually needs.'},
    ],
    colourAngle:{
      red:'Reds default to a directing style and must actively learn to flex toward supporting and coaching — particularly for experienced team members who need autonomy, not instruction. Being told what to do by a Red when you\'ve been doing the job for 10 years is demotivating in the extreme.',
      yellow:'Yellows default to an inspirational, people-led style that lands well for motivated high-performers — but poorly for someone who needs structure, clear expectations, and consistent follow-through rather than enthusiasm.',
      green:'Greens default to supporting and accommodating — often the right move for building psychological safety, but insufficient when someone needs a direct challenge, a hard deadline, or unambiguous feedback to grow.',
      blue:'Blues offer a careful, structured coaching approach for competence development — but can be overly directive about process and simultaneously too passive about interpersonal dynamics, leaving the relational dimension of leadership unattended.',
    },
    leaderInAction:'A manager has two direct reports at opposite ends of the development spectrum: a new graduate who needs daily direction and a 10-year expert who resents being told what to do. She realises she has been using the same management style for both — tight check-ins, structured agendas, weekly one-to-ones with the same format. The expert has started disengaging. She shifts to results-only conversations with the expert and reserves the structured cadence for the new joiner. Both relationships improve noticeably within a month. The inputs to the change were zero — only the style of engagement shifted.',
    watchOut:['Applying your own preferred communication style to everyone — this is efficient for you and often wrong for them.','Using the colour model as a reason to avoid stretching into someone\'s style — "I\'m not naturally Yellow so I don\'t do that" is the model turned into an excuse.','Adapting your words without adapting your assumptions — the language can change while the judgement behind it stays exactly the same.'],
  },
  8:{
    keyModels:[
      {name:"Cialdini's Six Principles of Influence",desc:'Reciprocity (give first), commitment (people follow through on stated positions), social proof (people follow what others do), authority (people defer to credible experts), liking (people comply with people they like), and scarcity (things feel more valuable when limited). Each can be applied ethically to build influence without positional power.'},
      {name:'Push vs. Pull Influence',desc:'Push influence — making an argument, asserting a position — is visible and often triggers resistance. Pull influence — asking questions, creating conditions for others to arrive at your conclusion themselves — is less visible and more durable. The most effective influencers mix both, reading which mode the situation and the person call for.'},
      {name:'The Trust Equation (Maister, Green & Galford)',desc:'Trust = (Credibility + Reliability + Intimacy) ÷ Self-Orientation. Leaders who are visibly advancing their own agenda destroy trust even when they are credible and reliable. Reducing self-orientation — genuinely caring about the other person\'s outcome — has the largest single impact on trust.'},
    ],
    colourAngle:{
      red:'Reds influence by driving for the result and making the decision obvious — highly effective with other Reds but alienating to those who need to feel part of the process. Pull influence feels inefficient to Reds but lands far more durably across a diverse stakeholder set.',
      yellow:'Yellows influence through energy and inspiration — highly effective in vision-setting and with people-focused stakeholders but insufficient for analytical audiences who need evidence, not enthusiasm. A strong Yellow pitch without data often loses Blue stakeholders entirely.',
      green:'Greens influence through relationship capital — they build trust patiently and draw on it when they need to move something. Their challenge: they may wait too long to use it, missing the timing window when their relational credibility would have made the difference.',
      blue:'Blues influence through evidence and rigorous logic — highly credible to analytical audiences but often underweighted on the emotional and relational signals that also drive decisions. A flawless analysis delivered without warmth or narrative loses half its power.',
    },
    leaderInAction:'A product manager needs engineering resource for a project she does not own and has no authority over. Rather than escalating, she spends three weeks genuinely understanding the engineering lead\'s team constraints, deadlines, and priorities. She then frames her request in terms of what it solves for him — reduced scope creep in Q4 — and brings early user data that makes the impact concrete. The engineering lead allocates 20% capacity to her project the following sprint, unprompted. No escalation, no politics — just influence built on understanding.',
    watchOut:['Escalating when influence fails — it signals an inability to work across boundaries and burns the goodwill that a future request depends on.','Pitching from your own colour — leading with evidence to a Yellow or emotional narrative to a Blue loses the audience before the substance lands.','Confusing being liked with having influence — people may genuinely enjoy your company and still not prioritise your work.'],
  },
  9:{
    keyModels:[
      {name:'Crucial Conversations (Patterson, Grenny et al.)',desc:'A framework for high-stakes, emotionally charged conversations — holding the space safe for genuine dialogue while surfacing hard truths. The central move: "start with heart" by clarifying your own intent before entering the conversation. If your intent is to win, the conversation will produce defensiveness rather than movement.'},
      {name:'SBI Feedback Model (Center for Creative Leadership)',desc:'Situation–Behaviour–Impact: anchor feedback in observable specifics (the Situation and the Behaviour observed) before naming the effect (the Impact). Removing interpretations keeps the conversation factual and reduces the defensiveness that makes feedback conversations unproductive.'},
      {name:'The Ladder of Inference (Argyris)',desc:'The brain leaps from raw data to conclusions in milliseconds, adding interpretations and assumptions invisibly along the way. In difficult conversations, walking back down the ladder — from conclusion to observed fact — reduces the defensiveness that springs from feeling judged rather than heard.'},
    ],
    colourAngle:{
      red:'Reds initiate difficult conversations early — sometimes before enough data is gathered — and may approach them too directly, triggering defensiveness. Their challenge: slowing down enough to hear the other person\'s perspective before making their own point.',
      yellow:'Yellows wrap the hard message in so much positive framing that the core point is lost. The person leaves the conversation feeling good about the relationship but with no clear idea that their behaviour needs to change.',
      green:'Greens are most prone to avoidance — the longer they wait, the higher the emotional stakes feel, and the harder the conversation becomes. Their silence is often mistaken for consent by the very person whose behaviour is the problem.',
      blue:'Blues over-prepare with data and reasoning but can come across as presenting a case rather than having a conversation — the other person feels judged and analysed rather than heard and engaged.',
    },
    leaderInAction:'A team lead has been avoiding a conversation with a colleague whose dismissive tone in retrospectives is shutting down the team\'s safety. The avoidance has lasted three months. She finally uses SBI: "In last Tuesday\'s retrospective, you dismissed two different ideas from the team with a laugh before they were finished. I noticed three people went quiet and haven\'t spoken in the last two retrospectives. I need to understand what was going on for you in that moment." The colleague did not know the impact. He is genuinely willing to change. The conversation that was avoided for three months takes 25 minutes and produces a real shift.',
    watchOut:['Waiting for the perfect moment — it never arrives, and the cost of waiting is paid by every person around the unaddressed issue.','Stating your interpretation as fact — "you\'re being defensive" instead of "when I see X, I read it as Y."','Resolving the conversation too quickly to avoid discomfort — sustainable change requires sitting in the difficulty long enough for real understanding to develop on both sides.'],
  },
};// Chapters 10–17
Object.assign(window.CHAPTERS_EXTRA, {
  10:{
    keyModels:[
      {name:'BLUF: Bottom Line Up Front',desc:'A military communication principle now standard in executive communication: state the conclusion or recommendation first, then provide supporting detail for those who need it. Reverses the natural instinct to build to the point — which wastes executive attention and buries the decision inside context.'},
      {name:'The 7-38-55 Rule (Mehrabian — with caveats)',desc:"Mehrabian's research showed that emotional communication is conveyed through words (7%), tone (38%), and body language (55%) — specifically for feelings and attitudes, not content. The practical principle: delivery shapes reception, especially in high-stakes moments where the room is forming a judgement about you as much as about your content."},
      {name:'Executive Presence Framework (Hewlett, 2014)',desc:'Gravitas (how you act), communication (how you speak), and appearance (how you look). Gravitas accounts for the largest share of perceived executive presence — built on composure under pressure, decisiveness, and the willingness to hold a position when challenged.'},
    ],
    colourAngle:{
      red:'Reds have natural presence — direct, decisive, confident. Their communication risk is a brevity that reads as dismissiveness and an energy that fills rooms so completely that others stop contributing. Managing the space you take, not just the content you bring, is the Red\'s core communication development.',
      yellow:'Yellows are natural communicators — engaging, energetic, warm. Their presence risk is losing credibility with analytical audiences who experience enthusiasm without precision as a sign that the underlying work is soft. Pairing energy with evidence solves this.',
      green:'Greens\' presence challenge is quiet authority — they often have the substance but may not project the confidence. Learning to take space, hold eye contact, and hold a pause (rather than filling it) builds the perception that their competence already deserves.',
      blue:'Blues present with rigour and precision but can lose rooms by leading with data before context — and by underusing the emotional and narrative signals that make facts feel trustworthy rather than merely accurate.',
    },
    leaderInAction:'A manager presents a project recommendation to the executive team for the first time. She knows the technical detail cold — 47 slides, thorough background, strong analysis. On slide 3 she notices the CEO checking her phone. The next month, she restructures every executive communication around BLUF: recommendation in one sentence on slide one, decision required stated explicitly, key risks as three bullets. The same CEO stops to ask clarifying questions instead of disengaging. The content did not change. The structure did.',
    watchOut:['Presenting information in the order you discovered it — logical to you, inefficient for your audience.','Filling silence with words — pauses signal confidence; rushed words signal anxiety. The pause is doing the work, not undermining it.','Confusing expertise with presence — knowing more than anyone in the room does not automatically make you the most credible person in it.'],
  },
  11:{
    keyModels:[
      {name:"Google's Project Aristotle (2016)",desc:"A five-year study of 180 Google teams found that who is on the team matters less than how the team works together. Of the five factors identified, psychological safety was the most important by a significant margin — without it, the other four factors couldn't function."},
      {name:'The Five Dysfunctions of a Team (Lencioni, 2002)',desc:'A pyramid of compounding dysfunction: absence of trust → fear of conflict → lack of commitment → avoidance of accountability → inattention to results. Each layer cascades from the layer beneath it. You cannot fix accountability without first building the trust and productive conflict that make accountability feel safe rather than punitive.'},
      {name:"Hackman's Conditions for Team Effectiveness",desc:'Richard Hackman identified five enabling conditions: real team (stable membership with clear boundaries), compelling direction, enabling structure, supportive organisational context, and expert coaching. Leaders create conditions — they do not produce performance directly. The mistake is managing outputs rather than building the conditions that produce outputs.'},
    ],
    colourAngle:{
      red:'Red-led teams often deliver strong results under pressure but may underinvest in the relational foundations — trust and psychological safety — that sustain performance over time and through adversity.',
      yellow:'Yellow-led teams have strong energy, creativity, and cohesion — great on the safety and morale dimensions — but may lack the operational rigour (clear goals, follow-through systems, accountability conversations) that converts enthusiasm into consistent delivery.',
      green:'Green-led teams have high psychological safety and strong relationships but can struggle with productive conflict — issues surface slowly, dissent is softened rather than named, and decisions take longer than necessary.',
      blue:'Blue-led teams have strong process discipline and quality standards but may feel procedurally rigid — people follow the system rather than taking ownership of the outcome, and innovation is suppressed in the interest of consistency.',
    },
    leaderInAction:'A newly appointed team lead inherits a high-output, low-trust team. Delivery is strong but people do not ask each other for help, and retrospectives are clean and performative rather than honest. She introduces one change: a 5-minute "what am I struggling with this week" at the start of Monday standups — and she models it first, naming a real problem she has not solved and asking for input. Six weeks later two senior engineers are proactively pairing on problems neither one was required to share. The safety she modelled is now the safety they practice.',
    watchOut:['Assuming a team that delivers results is a high-performing team — the conditions may be fragile, and the first disruption will reveal which pillars are missing.','Trying to fix all four pillars simultaneously — pick the weakest one and build from there; intervening on everything at once produces confusion rather than progress.','Treating team rituals as administrative overhead — they are the mechanism through which the conditions for performance are maintained, not a byproduct of performance.'],
  },
  12:{
    keyModels:[
      {name:'Psychological Safety (Edmondson, 1999)',desc:"Amy Edmondson's Harvard research, later made famous through Google's Project Aristotle, defines psychological safety as the shared belief that the team is safe for interpersonal risk-taking. It predicts team learning, quality improvement, and innovation — and is distinct from trust (which is about individual relationships) because it is a property of the whole group."},
      {name:'The Trust Battery (Lütke, Shopify)',desc:'Every interaction either charges or drains a trust battery. Reliability, transparency, and directness charge it; inconsistency, hidden agendas, and avoidance of hard truths drain it. The battery level determines how much latitude people extend you when things go wrong — and how quickly they assume good intent when communication is ambiguous.'},
      {name:'Safety + Accountability Matrix (Edmondson)',desc:'High performance lives in the quadrant of high psychological safety AND high standards simultaneously. High safety alone produces comfort but not growth. High standards alone produce anxiety and error-hiding. The combination — feeling safe to speak up within a culture of genuine accountability — is where sustained high performance becomes possible.'},
    ],
    colourAngle:{
      red:'Red-dominant team cultures produce strong accountability but often insufficient safety — standards are clear, but people are afraid to admit mistakes or surface problems early, meaning issues compound before they are seen.',
      yellow:'Yellow-dominant cultures feel safe, enjoyable, and creative — but may lack the honest challenge that makes safety productive. People say yes in the room and worry privately; the discomfort is outsourced to hallway conversations rather than resolved in the team forum.',
      green:'Green-dominant cultures produce warmth and interpersonal safety but can become conflict-avoidant — difficult truths are softened until they lose their useful sharpness, and performance issues fester under the guise of kindness.',
      blue:'Blue-dominant cultures value correctness — which can inadvertently punish imprecision. People stop experimenting or asking naive questions because they fear appearing uninformed in front of a rigorous, detail-oriented team.',
    },
    leaderInAction:"A VP of Engineering notices that incidents are always reported by the same three engineers, and that post-mortems consistently arrive at clean, non-specific conclusions. He suspects people are managing up rather than being honest. He runs a blameless post-mortem where he walks through his own architecture decision from the previous quarter — a decision that created a significant technical debt — in detail, in front of the team, naming exactly where his reasoning was flawed. Over the following two months, incident reports triple. The incidents were always there. The safety to name them was not.",
    watchOut:['Measuring psychological safety by whether meetings feel comfortable — comfortable meetings can still be low-safety if the real discomfort is voiced only in hallway conversations after the meeting ends.','Believing that being approachable and kind is the same as having created psychological safety — safety is demonstrated by what happens when someone brings bad news, not by how friendly the team culture feels.','Conflating safety with performance — a team can feel very psychologically safe and still be chronically underdelivering against its potential.'],
  },
  13:{
    keyModels:[
      {name:'The Operating Cadence',desc:'High-performing organisations run on a predictable rhythm of rituals — quarterly, monthly, weekly, daily — that create a heartbeat of progress visibility and course correction. The cadence replaces anxious chasing with calm, predictable checkpoints where the team self-corrects rather than waiting for the leader to notice a problem.'},
      {name:'Meeting Design Principles',desc:'Effective meetings have a single owner, a clear and singular purpose, the minimum necessary attendees, and either a decision to make or a specific update to give — not both in the same session. Combining decision-making with status updates produces meetings that do neither well and waste everyone\'s time in doing so.'},
      {name:'The Accountability Dial (Newberry & Taplett)',desc:'A five-step accountability conversation progression: mention → remind → confront → consequence → release. Leaders who skip to consequence too early create fear rather than accountability. Leaders who stay permanently at mention signal that commitments are optional. Moving deliberately through the dial builds accountability while preserving safety.'},
    ],
    colourAngle:{
      red:'Reds create accountability through direct confrontation — effective, but potentially threatening in a team that needs psychological safety. Their operating rhythm can also feel relentlessly high-intensity, leaving no space for reflection or recovery.',
      yellow:'Yellows create energy and connection in rituals but may let accountability slide in the service of maintaining positivity. Commitments made in Yellow-led team meetings often need a separate, structured follow-up mechanism to actually close.',
      green:'Greens build reliable rhythms with consistent follow-up — but avoid the accountability moment when it matters most: the direct, specific conversation that names the consequence of repeated missed commitments.',
      blue:'Blues create rigorous, documented rhythms and excellent process — but can over-engineer the system, producing meeting overload that drains the team\'s time and energy away from the actual work they are supposed to be doing.',
    },
    leaderInAction:'A team lead realises that his weekly sync has morphed into a 90-minute status report where he is the only person asking questions and team members are reading from notes prepared the night before. He redesigns the cadence: a 15-minute blockers-only standup on Monday, a 30-minute decision forum on Wednesday (only items requiring group input, no updates), and a monthly retrospective with genuine questions rather than a template. Total meeting time drops from 90 minutes to 60 minutes per week. The quality and usefulness of each conversation increase significantly because each has a single, clear purpose.',
    watchOut:['Creating a rhythm that exists to show progress to the leader rather than to enable the team to self-correct — the ritual serves the leader\'s information need rather than the team\'s operating need.','Treating the rituals as bureaucratic overhead when they are running smoothly — smooth-running rituals are the signal that the system is working, not that the system is no longer needed.','Separating accountability from support — holding someone accountable for an outcome without understanding what they need to be set up for success is punishment rather than leadership.'],
  },
  14:{
    keyModels:[
      {name:'OKRs (Doerr — from Intel/Google)',desc:'Objectives and Key Results: an Objective is a qualitative, directional statement of ambition that motivates; Key Results are 3–5 measurable outcomes that define precisely what "done" looks like. OKRs are more flexible than fixed KPIs — they are intended to stretch and are revisited quarterly rather than annually.'},
      {name:'SMART Goals (Doran, 1981)',desc:'Specific, Measurable, Achievable, Relevant, Time-bound — still the most widely used goal framework. Most real-world goal failures occur at the first two criteria: insufficient specificity (so ownership is diffuse) and unmeasured success criteria (so completion is a matter of interpretation rather than evidence).'},
      {name:'Goal-Setting Theory (Locke & Latham, 1990)',desc:'Empirical research showing that specific, challenging goals produce significantly higher performance than vague or easy goals — when combined with feedback and genuine commitment. The finding is robust across cultures and contexts. Excessively difficult goals produce anxiety rather than motivation — the stretch must be credible.'},
    ],
    colourAngle:{
      red:'Reds set goals ambitiously and drive hard toward them — but may set goals that are clear on outcome and vague on method, leaving the team uncertain about how to deliver without the Red\'s direct involvement at every decision point.',
      yellow:'Yellows set inspiring, motivating goals — but often under-specify the measurable success criteria. The team is energised, but success gets celebrated before it is actually achieved because "better" and "improved" were never defined precisely enough to verify.',
      green:'Greens set achievable, relationship-respecting goals — but often set them too conservatively, underestimating what the team can do in the interest of building confidence rather than stretching capability.',
      blue:'Blues set precise, well-evidenced goals — but can over-measure, defining so many key results and tracking mechanisms that the team spends more energy maintaining the measurement system than delivering the actual work.',
    },
    leaderInAction:'A product team\'s goal for Q3 is "improve customer onboarding." At the quarter\'s end, everyone claims success — but 90-day retention has not moved. A retrospective reveals that "improve" meant entirely different things to different people. The following quarter the team rewrites it: "Increase 90-day retention from 34% to 42%, measured in the weekly cohort analysis dashboard." Same team, no structural changes, no additional resource — the single act of specifying the outcome clearly enough to measure means everyone is working toward the same thing. The team hits 40% within 8 weeks.',
    watchOut:['Setting goals at the team level that cannot be owned by any individual — "increase revenue by 20%" with no single owner is a wish, not a goal.','Rewarding activity (features shipped, meetings held, tasks completed) rather than outcomes (impact on users, business value, measurable change).','Treating goal-setting as an annual ceremony rather than a living commitment reviewed and adjusted as context changes — goals set in January are often obsolete by March.'],
  },
  15:{
    keyModels:[
      {name:'One-Way and Two-Way Doors (Bezos, 2016)',desc:'Type 1 (one-way) decisions are irreversible or very hard to reverse — they require deliberation, data, and senior involvement. Type 2 (two-way) decisions can be undone quickly — they should be made fast, close to the work, without escalation. The most common organisational failure mode is treating all decisions as Type 1, producing slowness without any corresponding reduction in risk.'},
      {name:'The 70% Rule (Powell / Bezos)',desc:'Make a decision when you have approximately 70% of the information you wish you had. Below 40% is reckless. Above 70%, the cost of additional information — in time and opportunity — typically exceeds the value of the certainty it provides. The skill is calibrating where you are on that continuum.'},
      {name:'The Pre-Mortem (Klein, 2007)',desc:'Before committing to a decision, assume it has already failed and ask: "What went wrong?" This prospective hindsight technique surfaces risks that optimism hides — risks that are far harder to see when you are emotionally invested in the decision going forward. Teams consistently find more weaknesses through pre-mortems than through conventional risk-assessment.'},
    ],
    colourAngle:{
      red:'Reds decide fast — the right instinct for Type 2 decisions and a dangerous one for Type 1. Their speed is a genuine competitive advantage that also causes expensive mistakes on irreversible choices where the cost of additional deliberation is genuinely worth paying.',
      yellow:'Yellows decide optimistically — they underweight risks and overweight possibilities. The pre-mortem is especially valuable for Yellows because imagining failure is genuinely counter-intuitive for them; the technique gives the risk-surfacing process a structure that compensates for natural optimism.',
      green:'Greens seek consensus before deciding — invaluable for commitment and buy-in, but costly when the decision window is short. Learning to decide with 70% alignment rather than 100% agreement is one of the most important development edges for Green-dominant leaders.',
      blue:'Blues are the counterpart to Reds — they can wait too long for certainty that will not arrive. Their strength is catching the risks that Reds and Yellows miss; their challenge is accepting that imperfect information is the normal condition for any decision worth making.',
    },
    leaderInAction:'A leadership team has been debating a platform migration for six months — blocked on the need for "more data." A consultant asks one question: "Is this a one-way or two-way door?" After discussion, they agree it is a two-way door — they can roll back within two quarters if needed. With that reframe, the data they already have is sufficient for the level of confidence the decision requires. They decide in the same meeting, and the migration begins the following week. The data they were waiting for never would have changed the answer.',
    watchOut:['Treating every decision as a one-way door — the hallmark of slow, over-cautious organisations that mistake deliberation for rigour.','Deciding and then continuing to revisit the decision at every subsequent meeting — disagree and commit means actually committing, not reopening the discussion when it becomes inconvenient.','Confusing data with certainty — more data reduces ambiguity, it does not eliminate it. At some point, additional data is a form of avoidance.'],
  },
  16:{
    keyModels:[
      {name:'The GROW Model (Whitmore, 1992)',desc:'Goal → Reality → Options → Will (Way Forward). A coaching conversation structure that assumes the answer exists within the person rather than with the coach. Each stage is driven by questions rather than answers. The most common mistake: moving too quickly to Options before the person has genuinely assessed their current Reality.'},
      {name:'The Coaching Stance vs. The Expert Stance',desc:'The expert stance provides answers, frameworks, and direction — appropriate for mentoring, knowledge transfer, or genuine skill gaps. The coaching stance holds space for discovery — appropriate when the person already has the capability but lacks clarity, confidence, or ownership. The diagnostic question is: does this person lack knowledge, or do they lack ownership?'},
      {name:'Awareness + Responsibility (Whitmore)',desc:'Performance = Potential − Interference. Coaching works by raising awareness (so the person sees their situation more clearly) and building responsibility (so they own their next step). When both are present, the interference drops and performance follows automatically — without the leader having to drive it.'},
    ],
    colourAngle:{
      red:'Reds default to the expert stance efficiently — they give answers rather than asking questions. Coaching feels slow and indirect. But their direct reports often need the coaching experience to build genuine ownership rather than compliance that evaporates when the Red is not watching.',
      yellow:'Yellows enjoy coaching conversations and build rapport naturally — but may drift into storytelling and personal anecdote (mentoring) when the person actually needs the silence and open questions of a coaching conversation.',
      green:'Greens are naturally patient and supportive — qualities that make excellent coaches. Their challenge: they may be so careful not to push that they fail to name the limiting belief or the avoided step that is actually blocking the person\'s progress.',
      blue:'Blues run methodical, structured GROW conversations — precise and well-sequenced. Their challenge is holding the space for emotional insight once the logical problem is defined, rather than jumping to the solution as soon as the analysis is complete.',
    },
    leaderInAction:"A manager's star analyst says she doesn't think she's ready for a promotion. He has a choice: reassure her (mentoring) or coach her. He chooses to coach: 'Tell me what ready looks like to you.' She describes a specific set of skills. He asks: 'Which of those skills do you actually think you're missing right now?' A long pause. Then: 'Maybe none of them.' The conversation continues. She applies for the promotion two weeks later and is successful. He provided no answers, no reassurance, no evidence — only the questions that helped her find her own answer. The ownership she feels in the decision is what makes the difference in the role.",
    watchOut:['Defaulting to the mentor role when the person already has the capability — giving the answer steals their ownership and short-circuits the development that was possible.','Coaching when someone genuinely lacks knowledge — asking "what do you think you should do?" to someone who truly does not know the answer is frustrating and disrespectful, not empowering.','Ending the coaching conversation without a specific, committed next step — insight without action is the most common coaching failure, and the follow-through accountability is the coach\'s responsibility to create.'],
  },
  17:{
    keyModels:[
      {name:'The Culture Map (Erin Meyer, 2014)',desc:'Eight dimensions on which cultures differ systematically: communicating (explicit vs. implicit), evaluating (direct vs. indirect feedback), persuading (principles-first vs. applications-first), leading (egalitarian vs. hierarchical), deciding (consensual vs. top-down), trusting (task-based vs. relationship-based), disagreeing (confrontational vs. avoidant), and scheduling (linear vs. flexible). The map provides a precise vocabulary for differences that are otherwise felt but unnamed.'},
      {name:"Hofstede's Cultural Dimensions",desc:"Six macro-level dimensions: Power Distance (acceptance of unequal distribution of power), Individualism–Collectivism, Masculinity–Femininity, Uncertainty Avoidance, Long-Term vs. Short-Term Orientation, and Indulgence vs. Restraint. Most useful as a calibration tool for broad expectations — not for predicting any individual's behaviour."},
      {name:'The Two-Layer Model',desc:'Culture sets the baseline of what counts as "normal" behaviour in a given context; individual colour describes where a specific person sits relative to that baseline. A highly direct communicator in a reserved culture and a reserved communicator in a direct culture may produce communication that lands in exactly the same place — the layer model is what makes accurate diagnosis possible.'},
    ],
    colourAngle:{
      red:'Red behaviours — direct communication, fast unilateral decisions, explicit public disagreement — are high-status signals in some cultures (US, Netherlands, Germany, Israel) and read as rude or destabilising in others (Japan, Thailand, much of Southeast Asia). Reds operating internationally must diagnose the cultural register before deploying their default style.',
      yellow:'Yellow warmth and social investment is broadly appreciated across cultures — but the appropriate channels for expressing it (small talk before business, first-name informality, physical expressiveness, public emotional sharing) vary significantly and need calibration per context.',
      green:'Green harmony-seeking aligns naturally with high-context, relationship-first cultures — but Greens operating in low-context, direct-communication environments may be read as indirect, unclear, or evasive when they are simply attempting to be polite and considerate.',
      blue:'Blues\' preference for data, precision, and structured process aligns well with uncertainty-avoidant cultures that value rigor and planning — but sits poorly with relationship-first cultures that expect trust to be built through personal connection before process receives any respect.',
    },
    leaderInAction:'A team lead manages a distributed team with members in the Netherlands, Japan, and Brazil. In her first team-of-teams review she asks for candid input on a proposal and receives detailed, direct critique from her Dutch colleague, enthusiastic agreement from her Brazilian team, and silence from her Japanese colleague. She initially reads this as strong consensus. Three weeks later implementation stalls in Japan. In a one-to-one, her Japanese colleague explains the specific concerns she had on day one — which her silence had not communicated as objection. The lead redesigns her input process: written responses 48 hours before each meeting, with structured asynchronous input running alongside the live discussion, so the silence in the meeting no longer means consent.',
    watchOut:['Applying a cultural average to an individual — stereotyping cultures is as reductive and inaccurate as stereotyping colours.','Assuming that someone who speaks your language fluently also shares your cultural communication norms — language fluency and cultural fluency are independent.','Making your home culture\'s norms the invisible default — what feels like "appropriate directness" in one context reads as aggression or disrespect in another, and the gap is invisible until it does damage.'],
  },
  18:{
    keyModels:[
      {name:'The Eight Scales (Erin Meyer, The Culture Map, 2014)',desc:'Communicating (low- vs. high-context), Evaluating (direct vs. indirect negative feedback), Persuading (principles-first vs. applications-first), Leading (egalitarian vs. hierarchical), Deciding (consensual vs. top-down), Trusting (task-based vs. relationship-based), Disagreeing (confrontational vs. avoids-confrontation), and Scheduling (linear-time vs. flexible-time). Together they turn "we just clash" into eight specific, comparable axes you can actually work with.'},
      {name:'Relative positioning',desc:"Meyer's central rule: a culture only means something relative to another. British managers find Americans direct; Americans find the French indirect; the French find the Chinese indirect. Never read a position in absolute terms — read the gap between two points, one of which is always your own culture."},
      {name:'Culture vs. personality (the two layers)',desc:'The scales describe cultural averages; each individual sits somewhere around that average. Use the map to set expectations and interpret behaviour, never to predict or excuse a single person — doing that is just stereotyping with a diagram.'},
    ],
    colourAngle:{
      red:'Red directness and speed are prized in low-context, direct-feedback, top-down cultures (US, Germany, Israel) and read as aggressive or destabilising in high-context, confrontation-avoiding ones (Japan, Thailand, Indonesia). Reds must diagnose the register before deploying their default.',
      yellow:'Yellow warmth travels well, but its channels differ: relationship-first cultures expect personal investment before business, while task-based cultures can find early informality presumptuous. Read where trust is built before you try to build it.',
      green:'Green harmony aligns with high-context, consensual, confrontation-avoiding cultures — but in direct, egalitarian, principles-first settings the same care can read as vague, slow, or evasive rather than considerate.',
      blue:'Blue precision and process fit uncertainty-avoiding, linear-time cultures, but in relationship-based, flexible-time settings the same rigour can feel cold and rushed when trust has not been established first.',
    },
    leaderInAction:'A leader runs a project across Germany, Japan, and Brazil. She asks for candid feedback and gets blunt written critique from Berlin, warm verbal enthusiasm from São Paulo, and near-silence from Tokyo — which she reads as agreement. Weeks later Tokyo stalls; in a one-to-one her Japanese colleague lays out concerns she had held since day one, which the silence had not signalled as objection. The leader re-plots the team on the eight scales and redesigns the process: written input 48 hours ahead, and decisions confirmed explicitly rather than assumed from the room. The stall disappears — the difference was never talent or intent, only unread positions on the map.',
    watchOut:['Reading a position absolutely instead of relatively — "they are indirect" only means something next to a specific other culture, usually your own.','Applying a national average to the individual in front of you — the map sets expectations, it does not predict a person.','Assuming language fluency equals cultural fluency — a colleague who speaks perfect English may still operate by entirely different rules for feedback, hierarchy, and disagreement.'],
  },
});

// ── EXPANDED THEORY DEEP-DIVES ────────────────────────────────────────
// Each entry overrides the brief theory string in LANG_BOOK.en.chapters
// with a full pedagogical explanation of the underlying research.
(function(){
  var T={
    1:"Ram Charan, Stephen Drotter and James Noel's Leadership Pipeline framework identifies six distinct passages, each requiring new skills, new time horizons, and — hardest of all — new work values. The first passage, from individual contributor to first-line manager, is the most common site of leadership derailment: technically brilliant people who are promoted but continue solving problems themselves rather than developing others. Research shows most first-time leaders still derive more satisfaction from individual achievement than from growing their team, and this values misalignment — not a skills gap — is the root cause of failure. Peter Drucker observed that knowledge workers cannot be supervised the way manual workers can; they must be managed through clearly defined results. The leader's obligation shifts from delivering output to defining the right outcomes and creating the conditions under which others can achieve them. The deeper shift is psychological: the identity of 'the most capable person in the room' must be replaced by an identity built on enabling others to become the best version of themselves — a transition that many high-performers find genuinely difficult because it requires letting go of the very behaviours that earned them their position.",

    2:"The four-colour framework is a plain-language rendering of DISC, rooted in psychologist William Moulton Marston's 1928 work Emotions of Normal People. Marston proposed that behaviour maps onto two axes: whether a person experiences their environment as favourable or hostile, and whether they respond actively or passively. This produces four quadrants: Dominance (Red), Influence (Yellow), Steadiness (Green), and Conscientiousness (Blue). The model converges structurally with Social Styles (Wilson Learning), Insights Discovery, and the Jung-derived MBTI, providing some empirical confidence that the framework captures real clusters of behavioural preference. Crucially, DISC describes preference and default style — not ability, intelligence, or virtue. A high-Blue leader is not more rigorous than a high-Red leader; a high-Yellow leader is not warmer than a high-Green leader. Most people are a blend of two or more colours, with one or two dominant. Under stress, the shadow side of the dominant colour emerges: the style amplified, stripped of its positive intention, and operating with reduced self-awareness. The three rules that keep the model honest are: use it as a mirror, not a label; recognise that most people are a blend; and remember that no colour is inherently superior — high-performing teams need all four.",

    3:"Joseph Luft and Harrington Ingham's Johari Window maps self-knowledge across two dimensions — what is known to the self and what is known to others — producing four quadrants: Open (visible to both), Hidden (self knows, others do not), Blind Spot (others see it, the self does not), and Unknown (neither sees it). Feedback systematically shrinks the Blind Spot; self-disclosure shrinks the Hidden area. For leaders, the Blind Spot is the highest-risk zone because it contains the behaviours most likely to damage relationships and culture while operating entirely outside the leader's awareness. Tasha Eurich's 2017 research found that 95% of people believe they are self-aware but only approximately 10-15% meet the research criteria. More critically, internal self-awareness (understanding your values, emotions and patterns) and external self-awareness (knowing how others experience you) are barely correlated — a leader can be high on one and dangerously low on the other. Daniel Goleman positions self-awareness as the foundational competency of emotional intelligence: without it, no other emotional skill can reliably function, because you cannot regulate what you cannot see. The neurological reality is sobering: the brain's confirmation bias actively filters incoming information to reinforce existing self-beliefs, which is why deliberately seeking uncomfortable feedback from people who will tell the truth — and creating conditions where that feedback can reach you — is the only reliable mechanism for accurate self-knowledge at senior levels.",

    4:"Daniel Goleman's 1995 synthesis proposed five emotional intelligence domains: self-awareness (recognising emotions as they arise), self-regulation (managing them effectively), motivation (sustaining internal drive beyond external rewards), empathy (reading others' emotional states accurately), and social skill (building and managing relationships). Goleman argued that EI accounts for approximately 58% of performance in all job types, with the proportion rising in senior leadership roles where technical expertise becomes less differentiating. The neuroscientific foundation rests on the interplay between the limbic system, centred on the amygdala (the emotional alarm system), and the prefrontal cortex (the rational, deliberating brain). Joseph LeDoux's research showed that sensory information reaches the amygdala before the cortex — emotion arrives before rational thought — which is why Goleman coined 'amygdala hijack' for moments when the emotional brain overrides deliberate thinking entirely. Mayer, Salovey and Caruso's parallel four-branch ability model — perceiving emotions accurately, using emotions to facilitate thought, understanding emotional complexity, and managing emotions strategically — offers a measurable alternative to self-report approaches and has been validated across multiple independent research programmes. The critical practical implication is that all five of Goleman's domains are trainable: EI is not a fixed trait determined at birth but a set of practised capabilities that develop through deliberate attention, honest feedback, and repeated application in high-stakes situations.",

    5:"James Gross's Process Model of Emotion Regulation distinguishes antecedent-focused strategies — which intervene before an emotion fully forms — from response-focused strategies, which attempt to suppress or modify expression after the emotion has already peaked. Cognitive reappraisal, an antecedent strategy, reframes the meaning assigned to a situation before the emotional response crests. Research consistently shows it produces better outcomes for wellbeing, cognitive capacity, and relationship quality than suppression, while costing significantly less cognitive energy. Suppression does not eliminate emotion — it stores it, often expressing it through micro-signals that are visible to others even when the leader believes they are hidden. Dan Siegel's 'window of tolerance' describes the bandwidth of physiological arousal within which a person can function effectively: too activated (fight or flight), or too shut down (freeze), and executive function degrades. His 'hand model of the brain' illustrates how stress literally disengages the prefrontal cortex from the limbic system, explaining why intelligent people under pressure regress to reactive behaviour. Emily and Amelia Nagoski's stress cycle research establishes that the biological stress response must be physically completed — through movement, controlled breathing, or genuine social connection — to prevent chronic physiological dysregulation. For leaders, this means composure is not a performance but a physiology: the practices that build and maintain the window of tolerance (exercise, sleep, recovery) are the infrastructure of sustainable leadership effectiveness, not optional lifestyle choices.",

    6:"Goleman and Boyatzis distinguish three types of empathy: cognitive empathy (understanding how another person thinks and views the world), emotional empathy (feeling what they feel, mediated by the brain's mirror neuron systems), and empathic concern (sensing what they need and being genuinely moved to help). Leadership requires all three in calibrated balance — emotional empathy without cognitive control produces over-identification and emotional contagion; cognitive empathy alone, without concern, can become sophisticated manipulation. Carl Rogers' principle of unconditional positive regard — genuinely believing in the other person's worth and capacity regardless of their current behaviour — is the attitudinal foundation that distinguishes empathic listening from its performance. Howard Beckman and Richard Frankel's research on physician communication found that doctors interrupt patients an average of 23 seconds into their account — before the patient has communicated their actual concern. The same pattern is documented in management conversations: leaders who are mentally formulating a response before the other person has finished speaking are not listening empathically, even when they appear to be. Brené Brown's distinction between empathy (entering the other's perspective without judgement) and sympathy (commenting on the situation from outside it) clarifies why well-meant responses so often land as dismissive — 'at least you...' is a sympathy move that inadvertently reduces rather than acknowledges. The research finding with the most direct leadership application is consistent across studies: people accept difficult feedback and hard decisions significantly more readily from leaders they experience as genuinely understanding them, not because the decisions feel softer, but because the relationship feels safer.",

    7:"Hersey and Blanchard's Situational Leadership model (1969, substantially refined over subsequent decades) proposes that leadership effectiveness is a function of the match between the leader's approach and the follower's development level for a specific task. Development level combines competence (relevant skill and knowledge) with commitment (motivation and confidence), producing four stages: D1 (enthusiastic beginner — high commitment, limited competence), D2 (disillusioned learner — declining commitment as difficulty becomes apparent, growing competence), D3 (capable but cautious — high competence, variable commitment), D4 (self-reliant achiever — high on both). Each stage calls for a different leadership style: Directing (S1 — high task, low relationship guidance), Coaching (S2 — high task and relationship), Supporting (S3 — high relationship, low directive task guidance), Delegating (S4 — low on both, high autonomy). The most common destructive error is applying S1 direction to D4 people — providing step-by-step guidance to someone who already knows how to do the work signals distrust and produces disengagement at the exact moment maximum performance should be possible. The Platinum Rule — treat others as they want to be treated, not as you want to be treated — encapsulates the diagnostic stance required. Thomas and Kilmann's five conflict modes (Competing, Collaborating, Compromising, Avoiding, Accommodating) each have a legitimate application: Competing is appropriate in a genuine crisis requiring immediate decisive action; Collaborating is appropriate when both parties have high stakes and time allows; Avoiding is appropriate for trivial issues or when emotions need time to cool. The universal leadership failure is defaulting to a single preferred mode regardless of what the situation requires.",

    8:"Robert Cialdini's six principles of influence — reciprocity, commitment and consistency, social proof, authority, liking, and scarcity — each exploit a deep cognitive heuristic that evolved to enable fast, usually good-enough decisions in conditions of uncertainty. Reciprocity is particularly potent in leadership contexts: giving genuine value — genuine attention, useful insight, specific support, a well-placed referral — before making any request creates a psychological sense of obligation that scales with the relevance and quality of the gift. David Maister, Charles Green and Robert Galford's Trust Equation makes the components of trustworthiness precise: Trust = (Credibility + Reliability + Intimacy) / Self-Orientation. The denominator — self-orientation, meaning the degree to which a leader is visibly advancing their own interests — has a disproportionate destructive effect: a leader who is credible, reliable and warm but visibly self-serving generates far less trust than those scores should produce. Cohen and Bradford's influence currency model maps what different stakeholders value most — inspiration-related currencies (vision, excellence, moral purpose), task-related currencies (resources, information, access), position-related currencies (recognition, inclusion, visibility), and relationship currencies (understanding, safety, personal support) — and proposes that influence is the art of identifying and offering the currencies most valued by the specific person being influenced. Network research consistently shows that leaders positioned at the intersection of multiple groups — high in 'betweenness centrality' — are more effective at moving work across organisational boundaries than those with greater formal authority but narrower lateral networks.",

    9:"Patterson, Grenny, McMillan and Switzler's Crucial Conversations research found that the single most distinguishing capability of high-performing organisations is the ability to surface any undiscussable — any topic too sensitive, too risky, or too politically dangerous to raise — safely and productively. Their research documented that silenced conversations about performance, strategy, safety and relationships are the most direct predictor of organisational dysfunction, and that avoidance is not a neutral act: it compounds the problem while sending a message that it is either unimportant or too dangerous to name. The SBI feedback model (Situation, Behaviour, Impact), developed at the Center for Creative Leadership, anchors conversation in observable fact rather than interpretation, dramatically reducing defensive reactions by separating what was seen from what it might mean. Chris Argyris's Ladder of Inference (popularised by Peter Senge) shows how the mind invisibly adds interpretations, assumptions, and conclusions to raw data in milliseconds — and how deliberately walking a conversation back down the ladder, from 'you are disengaged' to 'in the last three meetings, I noticed you have not spoken,' reopens dialogue. Argyris's distinction between single-loop learning (adjusting behaviour to correct an error without examining its source) and double-loop learning (examining the governing assumptions that caused the error) is the difference between a conversation that changes action and one that changes understanding. Amy Edmondson's research confirms the practical consequence: in psychologically safe teams, problems surface early — when they are still cheap and easy to address — because people trust that the message will be received as information rather than as blame or threat.",

    10:"Albert Mehrabian's 1967 research is one of the most consistently misquoted findings in management literature. His actual finding was specific: when communicating feelings and attitudes, and specifically when verbal and non-verbal signals are in conflict, the emotional message is carried primarily by tone (38%) and body language (55%) rather than words (7%). The principle that delivery shapes reception — especially in high-stakes moments where credibility, intent and trustworthiness are being simultaneously assessed — is well-supported, even when those exact percentages do not generalise to all communication contexts. Aristotle's three modes of persuasion — ethos (credibility and demonstrated character), pathos (emotional resonance and relevance), logos (logical reasoning and evidence) — remain the most durable framework for understanding why some messages land and others do not. A message strong on logos but weak on ethos fails because the audience has not yet decided to trust the speaker; a message strong on pathos but weak on logos fails with analytical audiences who need evidence before commitment. BLUF (Bottom Line Up Front), a US military communication protocol, addresses the most common executive communication failure: burying the recommendation inside the evidence trail, requiring busy decision-makers to extract the point themselves. Sylvia Hewlett's research on executive presence across senior leadership populations identifies three components — gravitas (how you act, accounting for approximately 67% of the total impression), communication (how you speak and listen), and appearance (how you present yourself) — and shows that gravitas is built primarily through composure under pressure, decisiveness, and the willingness to hold a considered position when challenged, not through volume, assertiveness, or performance.",

    11:"Google's Project Aristotle (2012-2016), a study of 180 teams across engineering, sales and operations, found that standard variables — talent level, seniority, co-location, individual performance ratings — explained almost none of the variance in team effectiveness. The strongest predictor by a considerable margin was psychological safety: whether team members felt able to take interpersonal risks (asking naive questions, admitting mistakes, disagreeing with the leader, proposing unconventional ideas) without fear of punishment or humiliation. The other four factors identified — dependability, structure and clarity, meaning, and impact — depended on psychological safety as their foundation: without it, they could not function. Richard Hackman's decades of team research produced a conclusion that challenges most management intuition: 60% of team performance variance is determined before the team does any work, through the quality of its launch conditions, design, and initial alignment. His five enabling conditions are: a real team (clear, stable membership with genuine interdependence), a compelling direction (not 'be the best' but a specific, consequential outcome), an enabling structure (appropriate size, diversity, and clear norms), a supportive organisational context (information, resources, rewards that reinforce teamwork), and expert coaching available at the right moments. Patrick Lencioni's Five Dysfunctions pyramid builds causally from the base upward: absence of trust produces fear of conflict, which produces lack of commitment, which enables avoidance of accountability, which produces inattention to collective results. Each dysfunction is a symptom of the one beneath it — which is why teams that add accountability mechanisms without addressing the trust and conflict deficits underneath consistently fail to improve.",

    12:"Amy Edmondson coined psychological safety in a 1999 study of hospital nursing units, arising from a puzzling finding: the highest-performing units reported significantly more medical errors than the lowest-performing units. Investigation revealed the paradox: better teams reported more errors because they felt safe enough to do so — worse teams concealed them, allowing preventable harm to recur. She defines psychological safety as a shared belief that the team is safe for interpersonal risk-taking — specifically the risks of speaking up, admitting ignorance, challenging authority, and surfacing difficult truths. Her 2014 framework with Zhike Lei cross-tabulates psychological safety against performance standards, producing four zones: the Learning Zone (high safety, high standards) where sustained high performance is possible; the Comfort Zone (high safety, low standards) where wellbeing is present but growth stagnates; the Anxiety Zone (low safety, high standards) where errors are hidden and performance is brittle; and the Apathy Zone (low on both) where nothing meaningful is attempted. Paul Zak's neuroscience research identified eight management behaviours that reliably increase oxytocin — the neurochemical most directly associated with social trust — including recognising performance specifically, creating the right amount of challenge, giving genuine autonomy, sharing information broadly, and modelling vulnerability. His research showed organisations in the top quartile for trust outperformed the bottom quartile on virtually every relevant business metric. The practical implication is that psychological safety is not a cultural nicety but a structural precondition for the learning, error-catching, and innovation that sustained performance requires.",

    13:"Jim Collins and Jerry Porras, in Built to Last, describe clockwork precision — predictable, self-reinforcing rhythms of review and recalibration — as more characteristic of enduring high performance than individual leader brilliance or strategic vision alone. The agile software movement operationalised this insight into specific cadences that each serve a distinct coordination function: the 15-minute daily standup creates shared situational awareness and surfaces blockers before they compound; the sprint review creates accountability by making completed work visible to stakeholders; the retrospective examines process quality independently of output quality, enabling continuous improvement of how work is done. Meeting science research establishes that most meetings fail for two systemic reasons: they combine purposes that require incompatible formats (status sharing, real-time decision-making, and collaborative problem-solving have different participation requirements, different optimal group sizes, and different dynamics), and they include more participants than necessary for any single purpose. Patrick Lencioni's four-meeting model separates time horizons: daily check-in (5 minutes, logistics only), weekly tactical (45-90 minutes, agenda built from real-time obstacles), monthly strategic (2-4 hours, one or two big issues examined thoroughly), quarterly offsite (1-2 days, long-range thinking and team renewal). The Accountability Dial maps five conversational escalations from mention through consequence, and research on leader behaviour shows that permanent residence at the 'mention' level — raising an issue once without follow-through — reliably teaches the team that commitments are negotiable, while skipping directly to consequence without the preceding steps destroys the psychological safety that accountability depends on.",

    14:"Edwin Locke and Gary Latham's Goal-Setting Theory, built on more than 400 studies over 35 years, is among the most thoroughly validated frameworks in organisational psychology. Their meta-analysis established that specific, challenging goals produce on average 16% higher performance than vague or easy ones, operating through four mechanisms: directing attention toward goal-relevant activities and away from irrelevant ones, energising effort proportional to the goal's difficulty, increasing persistence in the face of obstacles, and motivating the development of relevant strategies and knowledge. Two moderating conditions are critical: commitment (the person must genuinely care about the goal, not just have accepted it) and feedback (they must know how they are doing against the goal continuously, not only at the end). John Doerr's OKR (Objectives and Key Results) methodology, derived from Andy Grove's Intel practice, operationalises the Locke-Latham findings: the Objective is a qualitative, inspiring statement of directional ambition; 3-5 Key Results are specific, time-bound, measurable outcomes that define what 'achieved' looks like concretely. OKRs are explicitly designed to stretch — Doerr recommends treating 60-70% achievement as a sign of appropriate ambition, with 100% achievement suggesting the target was not sufficiently challenging. Edward Deci and Richard Ryan's Self-Determination Theory adds a qualification that goal-setting research alone misses: goals imposed without autonomy, without personal meaning, or without clear rationale reduce intrinsic motivation over time even when they produce short-term performance. The implication is that how goals are set — through genuine dialogue, with explained reasoning, and with meaningful ownership — is inseparable from whether the goals produce the performance they were designed for.",

    15:"Jeff Bezos formalised the Type 1/Type 2 decision framework in Amazon's 2016 shareholder letter as a diagnosis of why large organisations become slow: they treat reversible (Type 2) decisions with the same deliberation required for irreversible (Type 1) ones. Type 1 decisions — high-stakes, hard to undo, requiring careful deliberation and senior involvement — are genuinely rare. Type 2 decisions — correctable quickly, requiring speed and proximity to information — are the majority of what leaders face. The disease is misclassification: treating Type 2 decisions as Type 1 produces drag without buying any additional certainty. Colin Powell's 40-70 rule operationalises the information threshold: gather between 40% and 70% of the information you wish you had, then commit. Below 40% is reckless; above 70% you have paid the cost of time without gaining certainty, because the remaining 30% of information rarely changes the decision and the competitive window may have closed. Gary Klein's Recognition-Primed Decision model, developed from fieldwork with firefighters and military commanders, shows that experienced decision-makers under time pressure rarely use analytical comparison of options. They pattern-match the situation to a prototype from prior experience, mentally simulate the most plausible option, and act if it holds up — adjusting as new information arrives. His Pre-Mortem technique (2007) operationalises prospective hindsight: before finalising a decision, the team imagines it has already failed and asks what went wrong. Independent research shows pre-mortems surface approximately 30% more potential problems than standard risk assessment because they dissolve the optimism bias and social pressure to support a decision that sets in once a course of action feels committed. Daniel Kahneman's System 1 (fast, intuitive, heuristic) and System 2 (slow, deliberate, analytical) framework explains why even highly intelligent leaders make poor decisions under pressure: System 1 generates the first answer, and System 2 rarely overrides it unless specifically prompted by a structured process.",

    16:"John Whitmore's GROW model — Goal, Reality, Options, Will (or Way Forward) — developed through the 1980s and published in Coaching for Performance (1992), is the most widely used coaching structure globally and the foundation of professional coaching practice. Its premise is that the answer to the person's challenge already exists within them; the coach's role is to create the conditions for that answer to surface, not to provide it. Whitmore's core equation, Performance = Potential minus Interference, reframes coaching's purpose: it works not by adding capability but by removing the self-doubt, self-criticism, and anxiety that prevent existing capability from expressing itself. Neuroscience research supports the questioning design of GROW: genuinely open, non-leading questions ('what would success actually look like?', 'what else might be possible?') activate the lateral prefrontal cortex and generate more novel, integrative thinking than closed or leading questions ('have you tried X?', 'don't you think Y would work?'), which shut the thinking down. Timothy Gallwey's Inner Game framework (The Inner Game of Tennis, 1974), which directly influenced Whitmore, provides the psychological mechanism: Self 1, the judging, critical inner voice, creates interference that prevents Self 2, the body's natural learning and performance capacity, from operating freely. Coaching quiets Self 1. The ICF core competencies — maintaining presence, deep listening, powerful questioning, direct communication when relevant, and creating awareness — formalise what distinguishes professional coaching from well-intentioned advice-giving. Research by the Manchester Consulting Group found professional coaching produces an average return of 5.7 times the investment across organisations. The critical diagnostic question that determines whether to coach or mentor is not about what the leader prefers, but about what the person actually needs: someone who lacks knowledge and experience needs a mentor who has already walked the path; someone who already has the capability but lacks clarity, confidence, or ownership needs a coach who will ask better questions than they are currently asking themselves.",

    17:"Erin Meyer's Culture Map (2014) identifies eight scales on which national cultures differ systematically and consequentially: Communicating (explicit/low-context, where meaning is stated in words, vs implicit/high-context, where meaning is conveyed through relationship, context, and non-verbal signal), Evaluating (direct negative feedback vs indirect), Persuading (principles-first vs applications-first), Leading (egalitarian vs hierarchical), Deciding (consensual vs top-down), Trusting (task-based, earned through demonstrated competence, vs relationship-based, earned through personal connection over time), Disagreeing (confrontational, where open debate is constructive, vs conflict-avoidant, where open disagreement threatens relationship), and Scheduling (linear-time, where structure and punctuality signal respect, vs flexible-time, where relationships and circumstances override fixed schedules). No position on any scale is inherently superior — each reflects rational adaptations to different historical, social, and economic conditions. Geert Hofstede's six cultural dimensions, derived from surveys of more than 116,000 IBM employees across 50 countries and expanded over subsequent decades, provide a macro-level complement: Power Distance (degree of acceptance of unequal authority distribution), Individualism vs Collectivism (whether identity and loyalty attach to the individual or the group), Masculinity vs Femininity (achievement and assertiveness orientation vs quality-of-life and cooperation orientation), Uncertainty Avoidance (tolerance of ambiguity and willingness to operate without rules), Long-term vs Short-term Orientation, and Indulgence vs Restraint. Edward Hall's foundational concept of high-context vs low-context communication, developed in the 1950s and 1960s, underlies much of Meyer's work and explains more intercultural misunderstanding than almost any other single variable — a direct communicator in a high-context culture who names a problem explicitly in a meeting may destroy relationships that a high-context communicator in the same room would have preserved through indirect signal. The adaptive leader's insight is that culture and individual behavioural style are two independent but complementary layers: culture sets the baseline of what counts as normal — appropriate directness, expected formality, comfortable pace, acceptable disagreement — while individual colour describes where a specific person sits relative to that cultural baseline. Reading only the individual misses the systematic patterns; reading only the culture stereotypes the individual. Both layers must be read together."
  };

  Object.keys(T).forEach(function(n){
    var key=+n;
    if(!window.CHAPTERS_EXTRA[key]) window.CHAPTERS_EXTRA[key]={};
    window.CHAPTERS_EXTRA[key].theory=T[n];
  });
})();
