// Doubles each chapter's theory deep-dive with a substantial second half of
// complementary frameworks. Per the project decision (2026-07-18), the new depth
// is authored in English and appended to EVERY locale (English fallback) until a
// proper translation is done; each locale keeps its existing translated intro.
// Idempotent — re-running is a no-op (marker: data-depth="2").
//   Run:  node scripts/double-theory.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const chDir = resolve(here, "..", "src", "lib", "chapters");
const LOCALES = ["en", "es", "it", "fr", "pt", "ar", "de", "zh", "ja", "ko"];

// Chapter number -> English HTML appended after the existing theory. The first
// element carries data-depth="2" as the idempotency marker.
const EXPANSIONS = {
  1: `<p data-depth="2"><strong>The transition has a shape you can plan for.</strong> Michael Watkins' <em>The First 90 Days</em> frames the move as a race to your <strong>break-even point</strong> — the moment you have contributed as much as you have consumed — and prescribes securing early wins, negotiating expectations with your boss, and diagnosing the situation (start-up, turnaround, realignment, or sustaining success) before acting. The classic failure is importing the strategy that worked in your last role into a situation that calls for a different one.</p><ul><li><strong>Levels of delegation (Tannenbaum &amp; Schmidt):</strong> delegation is a dial, not a switch — from "do exactly this" through "recommend and we decide together" to "decide, act, and tell me what happened." Matching the level to the person's competence on the specific task is what makes handing work off feel safe rather than reckless.</li><li><strong>Multipliers vs. Diminishers (Liz Wiseman):</strong> the best leaders get more capability out of people than they knew they had, while "accidental diminishers" — the always-on idea machine, the rescuer, the pace-setter — shrink the team precisely by being helpful. The shift from expert to leader is the shift from being smart to making others smart.</li></ul><p>Practically, the new role is a reallocation of time toward the few high-leverage activities — hiring, developing, setting direction, removing blockers — and away from the hands-on work that still feels like "real" progress. The discomfort of that trade is the job, not a sign you are doing it wrong.</p>`,
  2: `<p data-depth="2"><strong>Two axes explain most of the variance.</strong> Every four-quadrant model — DISC, Insights, Social Styles, even a plain reading of Myers-Briggs — rests on the same two questions: how a person spends energy (outgoing vs. reserved, fast vs. measured) and what they orient to first (task vs. people). Plot those and the four colours fall out; the label is just shorthand for a position on two dials.</p><ul><li><strong>Pace and priority:</strong> Reds and Yellows share a fast pace; Reds and Blues share a task priority. Knowing which dial you and the other person differ on tells you exactly what to adjust — slow down, or warm up.</li><li><strong>Behaviour, not character:</strong> the model describes preference, not ability or worth. A quiet Blue is not less committed than a loud Red; they show commitment in a different register, and reading register as commitment is the most common and most damaging misread.</li><li><strong>Colour under stress:</strong> pressure exaggerates the default (the driving Red turns autocratic, the amiable Green turns passive) or flips it entirely. Watch the shift — it is the most honest signal of what someone actually needs.</li></ul><p>The discipline is to hold a colour as a live hypothesis you keep testing, especially in writing and async channels where tone is stripped out and misreads multiply.</p>`,
  3: `<p data-depth="2"><strong>Self-awareness has two independent halves.</strong> Organisational psychologist Tasha Eurich's research separates <em>internal</em> self-awareness (seeing your own values, patterns, and impact clearly) from <em>external</em> self-awareness (knowing how others actually see you) — and finds they barely correlate. You can be rich in one and poor in the other, so a leader has to work both on purpose.</p><ul><li><strong>Ask "what", not "why":</strong> Eurich's studies show introspection often backfires — "why did I react like that?" invents plausible-but-wrong stories, while "what was I feeling, and what will I do next?" produces accurate, actionable insight.</li><li><strong>The Dunning-Kruger gap:</strong> the least skilled tend to over-rate themselves the most, because the competence to do a thing and the competence to judge it are the same competence. Seniority widens the gap rather than closing it, as candid feedback dries up the higher you rise.</li><li><strong>Loving critics:</strong> high-awareness leaders cultivate a few people who care about them <em>and</em> will tell them the truth, then respond with curiosity instead of defensiveness — which is what keeps the feedback coming.</li></ul>`,
  4: `<p data-depth="2"><strong>The mechanism is neurological, and the skill is trainable.</strong> Emotional signals reach the amygdala milliseconds before the prefrontal cortex, so under threat you feel before you think — the "hijack." The countermeasure is not willpower but a practised pause: <em>affect labelling</em> (Lieberman's "name it to tame it") measurably dampens amygdala activation and hands control back to the reasoning brain.</p><ul><li><strong>Ability model vs. mixed model:</strong> Salovey and Mayer frame EI as measurable abilities (perceiving, using, understanding, and managing emotion); Goleman's mixed model folds in competencies like motivation and social skill. Both agree the capabilities are learnable, unlike IQ, which plateaus early.</li><li><strong>Emotional contagion (Barsade):</strong> moods spread through a team like a virus, and the leader is the most infectious node. Your regulated calm — or your leaked anxiety — becomes the team's baseline, whether or not you intend it.</li></ul><p>This is why EI predicts leadership effectiveness more reliably than raw intellect at senior levels: the work is done through people, and people run on feeling first.</p>`,
  5: `<p data-depth="2"><strong>Regulation is a skill with a technique, not a fixed trait.</strong> James Gross's process model shows you can intervene at several points — before a trigger (choosing situations), during it (shifting attention), or after (reappraising meaning). The decisive finding: <em>cognitive reappraisal</em> (re-reading the situation) protects performance and relationships, while <em>suppression</em> (swallowing the feeling) raises your stress, leaks out anyway, and erodes trust.</p><ul><li><strong>The window of tolerance:</strong> everyone has a zone in which they can think and feel at once; past its edges you flip into fight-or-flight or shut down. Leaders learn their early warning signs and widen the window with sleep, breathing, and recovery.</li><li><strong>Body first, mind second:</strong> slow exhales, a sip of water, a short walk down-regulate the nervous system so the mind can re-engage — you cannot reason your way out of a hijack until the body settles.</li><li><strong>Co-regulation:</strong> a leader's visible composure signals to the group that the situation is survivable, which is often the single most useful thing you can offer in a crisis.</li></ul>`,
  6: `<p data-depth="2"><strong>Empathy is three distinct capacities, not one.</strong> Goleman and Ekman distinguish <em>cognitive</em> empathy (accurately taking a perspective), <em>emotional</em> empathy (feeling with someone), and <em>compassionate</em> empathy (being moved to help). Leaders need all three, weighted toward the first and third — perspective plus action — because unmanaged emotional empathy is where bias and burnout live.</p><ul><li><strong>Empathy vs. sympathy (Brené Brown):</strong> sympathy looks down and distances ("at least..."); empathy climbs into the hole and says "I know what it's like down here, and you're not alone." Sympathy protects you from discomfort; empathy connects at the cost of it.</li><li><strong>The limits of empathy (Paul Bloom):</strong> emotional empathy is a spotlight — it favours the person in front of you, people like you, the vivid over the statistical. Good leaders supplement it with compassion and fairness so they do not privilege the in-group by accident.</li><li><strong>Active-constructive responding (Shelly Gable):</strong> how you react to someone's <em>good</em> news predicts relationship strength more than how you handle their bad news — genuine, engaged celebration builds the trust that hard conversations later draw on.</li></ul>`,
  7: `<p data-depth="2"><strong>"Adaptive" has a second, deeper meaning.</strong> Beyond flexing style to the individual, Ronald Heifetz's <em>Adaptive Leadership</em> separates <strong>technical problems</strong> — solvable with known expertise — from <strong>adaptive challenges</strong>, which require people themselves to change beliefs, habits, or loyalties. The classic error is applying a technical fix (a new process, a smarter plan) to an adaptive problem that only shifts when the people do.</p><ul><li><strong>Get on the balcony:</strong> Heifetz's image for stepping off the dance floor to see the patterns — who is resisting, what is really at stake — before you intervene.</li><li><strong>Regulate the distress:</strong> adaptive work generates heat; the leader keeps it in a productive band — enough discomfort to force change, not so much that people flee or revolt.</li><li><strong>Transactional to transformational (Bass):</strong> the full range runs from exchange (clear expectations, contingent reward) up to inspiring purpose and individual development. Most situations need a blend; over-relying on either extreme is the trap.</li></ul>`,
  8: `<p data-depth="2"><strong>Influence has named mechanics you can practise.</strong> Robert Cialdini identifies seven levers of ethical persuasion: <em>reciprocity, commitment and consistency, social proof, authority, liking, scarcity,</em> and <em>unity</em> (shared identity). None require positional power; all can be earned. Used with integrity they open doors; used cynically they corrode the very trust they depend on.</p><ul><li><strong>Currencies of exchange (Cohen &amp; Bradford):</strong> influence without authority works by trading in the currencies the other person values — recognition, information, support, resources — which means first understanding what they need, not what you want.</li><li><strong>Bases of power (French &amp; Raven):</strong> positional power (reward, coercive, legitimate) is real but shallow; personal power (expert and referent — competence and relationship) is what lasts and what people follow by choice rather than obligation.</li><li><strong>Networks that reach (Ibarra):</strong> leaders build operational, personal, and strategic networks; the strategic one — future direction and sponsorship — is the most under-invested and the most decisive for influence.</li></ul>`,
  9: `<p data-depth="2"><strong>Hard conversations have a predictable anatomy.</strong> The Harvard model (Stone, Patton &amp; Heen) shows each one is really three at once: the <strong>"what happened"</strong> conversation (facts and blame), the <strong>feelings</strong> conversation, and the <strong>identity</strong> conversation (what this says about me). Most attempts fail because we argue the first while the real charge sits in the other two.</p><ul><li><strong>Make it safe (Crucial Conversations):</strong> people go silent or aggressive when they feel unsafe, so restoring safety — through mutual purpose and mutual respect — is the precondition for any honest exchange.</li><li><strong>Observation, not evaluation (Rosenberg's NVC):</strong> "you missed the last three deadlines" lands; "you're unreliable" triggers defence. Observation, feeling, need, request — in that order — keeps the conversation solvable.</li><li><strong>SBI:</strong> Situation-Behaviour-Impact gives feedback a spine — where and when, what you observed, and the concrete effect — specific enough to act on, neutral enough to hear.</li></ul>`,
  10: `<p data-depth="2"><strong>Presence is a composite you can build, not a gift you either have or lack.</strong> Sylvia Ann Hewlett's research breaks executive presence into three pillars: <strong>gravitas</strong> (how you act under pressure — the largest driver), <strong>communication</strong> (how you speak and hold a room), and <strong>appearance</strong> (a small but real gatekeeper). Gravitas dominates, which is good news: it is behavioural, and behaviour is trainable.</p><ul><li><strong>BLUF and the Pyramid Principle (Minto):</strong> lead with the answer, then support it — conclusion first, reasons grouped beneath, detail below that. Executives buy the headline first and drill down only if they choose to.</li><li><strong>Signpost and give the "so what":</strong> tell people where you are going ("three risks, one ask") and translate every fact into its implication. Data without a "so what" is noise dressed as rigour.</li><li><strong>Presence is physical:</strong> the pause, the slower cadence, the held silence after a key point signal composure more than any word. Filling every gap reads as anxiety; leaving space reads as authority.</li></ul>`,
  11: `<p data-depth="2"><strong>A team is a specific thing, not just a group.</strong> Katzenbach and Smith define a real team by a common purpose, shared goals, complementary skills, and — crucially — <em>mutual accountability</em>; a "working group" that merely coordinates individual outputs is not a team and should not be run like one. The leader's first job is to decide which the work actually needs.</p><ul><li><strong>The Five Dysfunctions (Lencioni):</strong> absence of trust breeds fear of conflict, then lack of commitment, then avoidance of accountability, then inattention to results. Because it stacks, you cannot fix the top without securing the base — vulnerability-based trust comes first.</li><li><strong>Tuckman's stages:</strong> forming, storming, norming, performing — most teams stall in "storming" and mistake the conflict for dysfunction, when it is a necessary passage to real norms.</li><li><strong>Size and social loafing (Ringelmann):</strong> per-person effort falls as teams grow because individual contribution becomes invisible; smaller teams with clear ownership beat large ones with diffuse responsibility.</li></ul>`,
  12: `<p data-depth="2"><strong>The evidence base here is unusually strong.</strong> Google's <em>Project Aristotle</em> studied hundreds of teams and found psychological safety was the single largest differentiator of high performers — above talent, resources, or tenure. It is not niceness; it is the shared belief that candour, questions, and admitting mistakes will not be punished.</p><ul><li><strong>The four stages (Timothy Clark):</strong> safety builds in order — <em>inclusion</em> (I belong), <em>learner</em> (safe to ask and fail), <em>contributor</em> (safe to add value), <em>challenger</em> (safe to question the status quo). You cannot expect challenge from people who do not yet feel included.</li><li><strong>The trust equation (Maister):</strong> Trust = (Credibility + Reliability + Intimacy) ÷ Self-Orientation. The lever most leaders ignore is the denominator — visibly caring about the other person's outcome does more for trust than any display of competence.</li><li><strong>Built in small moments:</strong> leaders manufacture safety by admitting their own errors, framing work as a learning problem, and meeting bad news with curiosity ("thank you for flagging that") rather than blame.</li></ul>`,
  13: `<p data-depth="2"><strong>Accountability is a system, not a personality.</strong> The <em>4 Disciplines of Execution</em> turn intentions into results: focus on one or two <strong>wildly important goals</strong>, act on the <strong>lead measures</strong> you can influence (not just lag results you can only watch), keep a visible <strong>scoreboard</strong>, and hold a short <strong>weekly cadence of accountability</strong> where people commit to next actions. The rhythm is what converts a good plan into delivered outcomes.</p><ul><li><strong>Clear ownership (RACI):</strong> for any commitment, name who is Responsible, Accountable, Consulted, and Informed. Most missed deliverables trace back to a shared assumption that someone else owned it.</li><li><strong>Radical candor (Kim Scott):</strong> effective accountability sits where caring personally meets challenging directly — challenge without care is obnoxious aggression; care without challenge is ruinous empathy that lets standards slide.</li><li><strong>After-action reviews:</strong> a blameless, standing ritual — what did we expect, what happened, why the gap, what will we change — turns every cycle into compounding learning instead of repeated surprise.</li></ul>`,
  14: `<p data-depth="2"><strong>The science of goals is settled, and specific-and-hard wins.</strong> Locke and Latham's goal-setting theory — among the most replicated findings in management — shows that specific, challenging goals produce higher performance than "do your best," provided there is commitment, feedback, and the capability to reach them. Vague or trivially easy goals quietly cap output.</p><ul><li><strong>Objectives and Key Results:</strong> an Objective is a qualitative, motivating direction; 3–5 Key Results are the measurable outcomes that define done. Aspirational OKRs are meant to stretch — a 70% hit is a win — and should be decoupled from compensation, or people sandbag them into safe targets.</li><li><strong>Outcomes over outputs over activity:</strong> "run four workshops" is activity; "ship the feature" is output; "cut onboarding time by 30%" is the outcome that actually matters. Goals set at the wrong altitude reward motion instead of results.</li><li><strong>Focus is the point:</strong> a goal system is as much about what it excludes as what it includes — a team chasing ten priorities has none.</li></ul>`,
  15: `<p data-depth="2"><strong>Good decisions fight predictable biases with structure.</strong> Kahneman's two systems — fast, intuitive System 1 and slow, effortful System 2 — explain why smart people decide badly: anchoring, confirmation bias, sunk-cost, and overconfidence run on autopilot unless a process interrupts them. Discipline is the set of habits that switch System 2 on for the decisions that warrant it.</p><ul><li><strong>One-way vs. two-way doors (Bezos):</strong> reversible decisions should be made fast and delegated; irreversible ones deserve slow, senior deliberation. Treating every decision as one-way grinds an organisation to a halt.</li><li><strong>Cynefin (Snowden):</strong> match the method to the terrain — <em>clear</em> problems follow best practice, <em>complicated</em> ones need expert analysis, <em>complex</em> ones require safe-to-fail experiments, and <em>chaotic</em> ones need action first to establish order.</li><li><strong>Premortems (Klein):</strong> before committing, imagine the decision has failed and ask why — surfacing the risks that optimism and groupthink would otherwise bury.</li><li><strong>Decide who decides (RAPID):</strong> naming who Recommends, Agrees, Performs, gives Input, and Decides kills the ambiguity that stalls decisions more often than the difficulty of the choice itself.</li></ul>`,
  16: `<p data-depth="2"><strong>Coaching is the discipline of talking less.</strong> Michael Bungay Stanier's <em>The Coaching Habit</em> compresses it to a reflex: stay curious a little longer, rush to action a little slower. His questions — "What's on your mind?" and the deceptively powerful "And what else?" — surface the real issue instead of the first one, and shift ownership to the other person.</p><ul><li><strong>The directive–non-directive spectrum (Whitmore):</strong> at one end you tell, at the other you ask; coaching lives toward the asking end, pulling insight out rather than pushing advice in. The GROW sequence (Goal, Reality, Options, Will) gives the conversation a spine.</li><li><strong>Ask vs. tell:</strong> advice creates dependence and is easy to ignore; a good question creates ownership and sticks, because people commit to conclusions they reach themselves.</li><li><strong>Levels of listening (Scharmer):</strong> most managers listen to confirm what they already think; real coaching listens to understand, and at its best listens for what is emerging that the person cannot yet articulate.</li></ul>`,
  17: `<p data-depth="2"><strong>Culture varies along mappable dimensions.</strong> Geert Hofstede's landmark research identified dimensions on which national cultures differ predictably — <em>power distance</em> (how much hierarchy is accepted), <em>individualism vs. collectivism, uncertainty avoidance, achievement vs. cooperation, long- vs. short-term orientation,</em> and <em>indulgence vs. restraint.</em> They describe averages, not individuals, but they explain why the same behaviour reads as confident in one country and arrogant in another.</p><ul><li><strong>Cultural intelligence (CQ — Earley &amp; Ang):</strong> the capability to work across cultures has four parts — the <em>drive</em> to engage, the <em>knowledge</em> of how cultures differ, the <em>strategy</em> to plan and check your reads, and the <em>action</em> to flex behaviour without losing yourself. Unlike a fixed trait, CQ grows through exposure and reflection.</li><li><strong>No centre of the map:</strong> the trap is treating your own culture as the neutral baseline against which others are "too direct" or "too slow." There is no centre — only positions relative to one another.</li></ul>`,
  18: `<p data-depth="2"><strong>The scales interact, and the interactions are where leaders get caught.</strong> Erin Meyer's real power is reading two dimensions together: a culture can be egalitarian in hierarchy yet consensual in decision-making (Sweden), or hierarchical yet top-down-fast (China) — combinations that defy the assumption that "flat equals fast." Trusting and disagreeing interact too: where trust is relationship-based, open confrontation can feel like a betrayal of the relationship rather than healthy debate.</p><ul><li><strong>Code-switching:</strong> global leaders do not adopt one culture; they build the range to move along each scale on purpose — more explicit here, more indirect there — while staying recognisably themselves.</li><li><strong>Build trust on the right foundation:</strong> in task-based cultures trust follows competent delivery; in relationship-based ones, business waits until trust is built over meals and time. Leading the second like the first reads as cold and transactional.</li><li><strong>Make the implicit explicit:</strong> the reliable move on any diverse team is to name the norm — how feedback is given, how decisions are made, how disagreement is voiced — rather than assume a shared default that does not exist.</li></ul>`,
  19: `<p data-depth="2"><strong>What makes ability actually grow is a mechanism, not a mood.</strong> Anders Ericsson's research on expertise shows the engine is <em>deliberate practice</em>: work at the edge of your current ability, with clear goals, immediate feedback, and repeated refinement — not hours logged, but focused, effortful, feedback-rich reps. A growth mindset is the belief that makes deliberate practice worth starting; deliberate practice is what turns the belief into results.</p><ul><li><strong>Effort plus strategy plus help:</strong> Dweck's later work stresses that a real growth mindset is not "try harder" but "try differently" — new strategies, seeking feedback, and asking for help. Praising effort that keeps failing is the "false growth mindset" wearing a badge.</li><li><strong>Intelligent failure (Amy Edmondson):</strong> not all failure is equal. Blameworthy failure (negligence) differs from the <em>intelligent failures</em> of well-designed experiments at the frontier — the kind a learning culture must celebrate, because they are the price of discovery.</li><li><strong>The learning organisation (Senge):</strong> Nadella scaled the mindset from person to enterprise — individual, team, and organisation — echoing Senge's point that the only durable advantage is learning faster than the competition. Curiosity, made systemic, becomes strategy.</li></ul>`,
};

const MARKER = 'data-depth="2"';
let changed = 0;

for (const loc of LOCALES) {
  const file = resolve(chDir, `${loc}.json`);
  const book = JSON.parse(readFileSync(file, "utf8"));
  let touched = false;
  for (const ch of book.chapters) {
    const add = EXPANSIONS[ch.number];
    if (!add) continue;
    if (typeof ch.theoryHtml !== "string" || ch.theoryHtml.length === 0) continue;
    if (ch.theoryHtml.includes(MARKER)) continue; // idempotent
    ch.theoryHtml += add;
    touched = true;
    changed++;
  }
  if (touched) writeFileSync(file, JSON.stringify(book, null, 2) + "\n", "utf8");
  console.log(`${loc}: ${touched ? "theory doubled" : "unchanged"}`);
}

console.log(`Done — ${changed} chapter theory sections expanded.`);
